repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: pytest-unit
        name: pytest -m unit
        entry: pytest -m unit -q
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-commit]
